stages:
  - init
  - build
  - deploy


workflow:
  rules:
    - if : '$CI_COMMIT_TAG =~ /^stage-/'
      when: always
    - if: '$CI_COMMIT_TAG =~ /^prod-/'
      when: always


init-job:
  stage: init
  script:
    - echo   "$CI_COMMIT_REF_NAME" | cut -d '-' -f1  >> .env
    - echo VERSION="$CI_COMMIT_REF_NAME" | rev |  cut -d '-' -f1 | rev >> .env
    - echo SERVICE="$CI_COMMIT_REF_NAME" |  sed 's/^\(stage\|prod\)-//' | sed 's/-[0-9.]*$//' >> .env
  artifacts:
    paths: ['.env']


build-job:
  stage: build
  before_script:
    - SERVICE=$(echo "$CI_COMMIT_REF_NAME" |  sed 's/^\(stage\|prod\)-//' | sed 's/-[0-9.]*$//')
    - TAG=$(echo "$CI_COMMIT_REF_NAME" | rev | cut -d '-' -f1 | rev)
    - export TAG
    - export SERVICE
  script:
    - echo $SERVICE
    - echo $TAG
    - docker -H 192.168.1.193:2375 build -t $SERVICE:$TAG .
  needs: 
    - init-job


deploy-job:
  stage: deploy
  needs: 
   - build-job
  before_script:
    - SERVICE=$(echo "$CI_COMMIT_REF_NAME" |  sed 's/^\(stage\|prod\)-//' | sed 's/-[0-9.]*$//')
    - TAG=$(echo "$CI_COMMIT_REF_NAME" | rev | cut -d '-' -f1 | rev)
    - export TAG
    - export SERVICE
    - pwd
    - whoami
    - hostname
  script:
    - docker-compose -H 192.168.1.193:2375 -f /srv/backup/docker-compose.yaml up  
  environment:
    name: stageing
  rules: 
    - if: '$CI_COMMIT_TAG =~ /^prod-/'
      when: manual
    - when: on_success
